#!/bin/bash -l
# Convert ptseries into pconns 
#attention: is missing motion file for now!!
subject_list=/home/rando149/shared/projects/rae_testing/nibabies_work/subject_list_ABCD.txt

#############################################################################################
# HARDCODED INPUTS
DERIVATIVESDIR=/home/rando149/shared/projects/rae_testing/nibabies_work/SfN_results/fMRIprep-LTS/
OUTDIR=/home/rando149/shared/projects/rae_testing/nibabies_work/SfN_results/fMRIprep-LTS/pconns
#paths to matlab runtime and wb_command
MRE_DIR='/home/feczk001/shared/code/external/utilities/MATLAB_MCR/v91/'
WB_CMD='/home/faird/shared/code/external/utilities/workbench/1.4.2/workbench/bin_rh_linux64/wb_command'
#############################################################
module load workbench/1.5.0; 
module load matlab; 

for n in {1..50}; do
SUB=$(echo | sed -n ${n}p ${subject_list})

#grep TR from ptseries
TR=$(wb_command -file-information ${DERIVATIVESDIR}/${SUB}_ses-baselineYear1Arm1_task-rest_run-1_Atlas_Gordon_incl_subc.ptseries.nii -only-step-interval) 

#run cifti-con for same amounts of data for each condition
python3 /home/faird/shared/code/internal/utilities/cifti_connectivity/cifti_conn_wrapper.py \
--mre-dir ${MRE_DIR} \
--wb-command ${WB_CMD} \
${DERIVATIVESDIR}/${SUB}_ses-baselineYear1Arm1_task-rest_run-1_Atlas_Gordon_incl_subc.ptseries.nii \
${TR} ${OUTDIR} matrix;

python3 /home/faird/shared/code/internal/utilities/cifti_connectivity/cifti_conn_wrapper.py \
--mre-dir ${MRE_DIR} \
--wb-command ${WB_CMD} \
${DERIVATIVESDIR}/${SUB}_ses-baselineYear1Arm1_task-rest_run-2_Atlas_Gordon_incl_subc.ptseries.nii \
${TR} ${OUTDIR} matrix;

done
